export const WRITER_DISTRIBUTION = {
  Local: ["Pelumi Ilesanmi"],
  "Across Africa": ["Pelumi Ilesanmi"],
  Global: ["Pelumi Ilesanmi"],
  Politics: ["Pelumi Ilesanmi"],
  Climate: ["Pelumi Ilesanmi"],
  Opinion: ["Owobu Maureen", "Ebasa Joseph", "Florence Idimone"],
  Startup: ["Ibukun-Oluwa Addy", "David Isong"],
  "Economy/Finance": ["Ibukun-Oluwa Addy"],
  Crypto: ["David Isong"],
  Career: ["Ibukun-Oluwa Addy"],
  "Latest Tech News": ["Uche Emeka"],
  AI: ["Uche Emeka"],
  Fintech: ["Uche Emeka", "David Isong"],
  "Social Insight": ["Owobu Maureen", "Florence Idimone", "Pelumi Ilesanmi"],
  Culture: ["Owobu Maureen", "Florence Idimone", "Pelumi Ilesanmi"],
  History: ["Owobu Maureen", "Florence Idimone", "Pelumi Ilesanmi"],
  "Diaspora Connect": ["Owobu Maureen", "Florence Idimone", "Pelumi Ilesanmi"],
  Science: ["Owobu Maureen", "Florence Idimone", "Pelumi Ilesanmi"],
  Health: ["Ibukun-Oluwa Addy", "Precious Eseaye"],
  Food: ["Ibukun-Oluwa Addy", "Precious Eseaye"],
  Travel: ["Ibukun-Oluwa Addy", "Precious Eseaye"],
  Parenting: ["Ibukun-Oluwa Addy", "Precious Eseaye"],
  Fashion: ["Ibukun-Oluwa Addy", "Precious Eseaye"],
  "Celebrity News": ["Precious Eseaye"],
  Profiles: ["Precious Eseaye"],
  Music: ["Precious Eseaye"],
  Movies: ["Precious Eseaye"],
  Sports: ["Uche Emeka", "Precious Eseaye"],
};
