# Explicitly add the 'curl' utility to our lean, professional kitchen
[phases.setup]
nixPkgs = ["...", "curl"]

# Define the command to start the application
[start]
cmd = "pm2-runtime start ecosystem.config.js"